In [ ]:
import numpy as np

In [35]:
q1 = np.arange(2, 17, 2)
Q1 = [q1[6], q1[2], q1[5]]


[14, 6, 12]

In [ ]:
q2 = np.array([[1, 3, 2], [0, 7, 4]])
Q2 = q1[q2]

In [ ]:
Q3 = q1.reshape(4, 2)

In [ ]:
Q4 = Q3[0, :][::-1]

array([4, 2])

In [ ]:
Q5 = Q3[:2, :1]

In [ ]:
np.random.seed(6)

In [ ]:
arr = np.random.randint(10, size = 10)

In [ ]:
Q6 = np.sort(arr)

array([0, 1, 1, 1, 3, 4, 4, 9, 9, 9])

In [ ]:
q7 = np.random.randint(10, size = (4,5))


In [ ]:
Q7 = np.sort(q7, axis = 0)

In [ ]:
Q8 = np.sort(q7, axis = 1)

array([[0, 3, 4, 9, 9],
       [1, 1, 1, 4, 9],
       [2, 2, 4, 5, 8],
       [2, 5, 5, 6, 9]])

In [ ]:
fruit = ['Grape', 'Apple', 'Banana']
color = ['Purple', 'Red', 'Yellow']
ranking = [3, 2, 1]

q9 = np.zeros(3, dtype = {'names':('fruit', 'color', 'ranking'),
                          'formats':('U20', 'U20', 'i4')})
q9['fruit'] = fruit
q9['color'] = color
q9['ranking'] = ranking

[('Grape', 'Purple', 3) ('Apple', 'Red', 2) ('Banana', 'Yellow', 1)]


In [27]:
Q9 = q9['color']

array(['Purple', 'Red', 'Yellow'], dtype='<U20')

In [25]:
Q10 = q9[2]

('Banana', 'Yellow', 1)

In [29]:
Q11 = q9[q9['ranking']<3]

array([('Apple', 'Red', 2), ('Banana', 'Yellow', 1)],
      dtype=[('fruit', '<U20'), ('color', '<U20'), ('ranking', '<i4')])