In [2]:
import numpy as np

In [6]:
np.random.seed(5)
arr = np.random.randint(15, size = (20))
Q1 = arr[3]


array([ 3, 14, 13,  6,  6,  0,  9,  8,  4,  7, 14, 11,  0, 14,  0,  7, 12,
        1,  5,  7])

In [7]:
Q2 = arr[8:]


array([ 4,  7, 14, 11,  0, 14,  0,  7, 12,  1,  5,  7])

In [9]:
index = [10, 3, 5, 7, 9, 11, 10, 15, 17]
Q3 = arr[index]

array([14,  6,  0,  8,  7, 11, 14,  7,  1])

In [18]:
np.random.seed(6)
arr2 = np.random.randint(15, size = (7, 8))
Q4 = arr2[5, 3]


5

In [18]:
Q5 = arr2[:2, 5:]

array([[13, 10,  0],
       [ 9, 10,  1]])

In [19]:
np.random.seed(10)
Q6 = np.random.randint(15, size = (4, 5))

array([[ 9, 13,  4,  0,  1],
       [11, 12,  9, 13,  0],
       [13,  1, 10,  8,  9],
       [ 0, 10,  8,  6,  4]])

In [20]:
Q6[2, 2] = 4
Q7 = Q6[1:, :3]

array([[11, 12,  9],
       [13,  1,  4],
       [ 0, 10,  8]])

In [22]:
np.random.seed(8)
Q8 = np.random.randint(15, size = (4, 5))

In [27]:
Q9 = np.array(Q8[1:, :3])
Q9[1,2] = 4

In [8]:
np.random.seed(20)
arr3 = np.random.randint(15, size = (2, 6)).reshape(4,3)
Q10 = arr3

In [12]:
np.random.seed(15)
Q11 = np.random.randint(15, size = 10).reshape(10,1)

array([[ 8],
       [ 5],
       [12],
       [ 5],
       [ 7],
       [ 0],
       [12],
       [11],
       [ 7],
       [11]])

In [16]:
np.random.seed(9)
arr4 = np.random.randint( 15, size = (5, 3))
Q12 = arr4[3, :].copy()

array([1, 6, 4])