In [1]:
import numpy as np

In [3]:
Q1 = np.zeros(20, dtype = float)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [5]:
Q2 = np.ones((4,5), dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [6]:
Q3 = np.full((2,5), 2.0, dtype = float)


array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [7]:
Q4 = np.arange(0, 50, dtype = float)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [9]:
Q5 = np.linspace(4, 18, 9)

array([ 4.  ,  5.75,  7.5 ,  9.25, 11.  , 12.75, 14.5 , 16.25, 18.  ])

In [12]:
Q6 = np.zeros((5,5), dtype = int)
np.fill_diagonal(Q6, 1)


array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [14]:
np.random.seed(10)
Q7 = np.random.rand(4, 2)

In [16]:
np.random.seed(9)
Q8 = np.random.randint(16, size = (4, 2, 5))

array([[[14, 12, 14,  5,  6],
        [ 8, 11,  6, 13,  1]],

       [[ 6,  4, 11,  8, 10],
        [ 1,  8,  5, 11,  1]],

       [[13, 12,  0, 12, 14],
        [11,  8, 10,  8, 13]],

       [[14, 10, 12,  8, 12],
        [ 2,  6,  8,  1,  8]]])

In [18]:
Q9 = Q8.size