In [2]:
import numpy as np

In [15]:
np.random.seed(56)
Q1 = np.random.randint(20, size = (10, 10))


array([[ 4, 15,  0,  2, 11, 14,  9,  4, 15, 17],
       [12,  2, 11, 11, 14, 16,  6,  1, 10,  5],
       [ 2, 15, 19,  5,  9,  2, 10,  1, 16, 13],
       [ 6, 18, 12,  0,  8,  4, 14, 15,  0, 17],
       [11, 17, 12, 19, 14, 10, 18,  1, 19,  3],
       [ 2,  0,  3, 16, 16,  8, 16,  9, 11,  0],
       [10, 18, 19,  7,  1, 11,  5, 16,  8,  2],
       [13,  8, 16, 19, 18,  7, 18,  5, 16, 14],
       [17,  1,  7, 15,  4,  1, 19,  2,  0,  8],
       [15, 16,  5, 19,  7,  7,  0, 15,  1, 19]])

In [4]:
Q2 = Q1[2:5, 3:8]


array([[ 5,  9,  2, 10,  1],
       [ 0,  8,  4, 14, 15],
       [19, 14, 10, 18,  1]])

In [5]:
Q3 = Q1[7:, 4:6]


array([[18,  7],
       [ 4,  1],
       [ 7,  7]])

In [6]:
Q4 = np.reshape(Q3, (2,3))


array([[18,  7,  4],
       [ 1,  7,  7]])

In [16]:

x = np.random.randint(15, size = 10)
y = np.random.randint(15, size = 10)
Q5 = np.concatenate((x, y), axis = 0)


array([ 5,  3,  2,  5,  1,  5,  1, 11, 14, 10,  4,  3,  9,  7,  6,  7,  7,
       14,  0,  4])

In [25]:
x1, x2, x3, x4 = np.array_split(Q5, [4, 11, 17])
Q6a = x1


array([5, 3, 2, 5])

In [26]:
Q6b = x2


array([ 1,  5,  1, 11, 14, 10,  4])

In [27]:
Q6c = x3


array([3, 9, 7, 6, 7, 7])

In [28]:
Q6d = x4


array([14,  0,  4])

In [31]:
Q7 = np.sum(Q5)


118

In [40]:
ran = np.random.randint(48, 85, size=50)
Q8 = np.mean(ran)
Q8


65.34

In [35]:
Name = ['Jonathan Loaisiga', 'Nick Saban', 'Katie Ladecky']
Occupation = ['Baseball player', 'Football coach', 'Swimmer']
Salary = [595800.00, 8619934.23, 100000.00]

In [38]:
sports = np.zeros(3, dtype = {'names':('Name', 'Occupation', 'Salary'),
                              'formats':('U20', 'U20', 'f8')})
sports['Name'] = Name
sports['Occupation'] = Occupation
sports['Salary'] = Salary

In [39]:
Q9 = sports


array([('Jonathan Loaisiga', 'Baseball player',  595800.  ),
       ('Nick Saban', 'Football coach', 8619934.23),
       ('Katie Ladecky', 'Swimmer',  100000.  )],
      dtype=[('Name', '<U20'), ('Occupation', '<U20'), ('Salary', '<f8')])